<?php

/*  UDEMY - PHP7 - SEGURANÇA
 *
 *	SESSION HIJACKING - ATAQUE A SESSÕES
 *	|	NUM SISTEMA HTTP, UM USUÁRIO MAL INTENCIONADO PODE ROUBAR O ID DE SESSÃO DE OUTRO USUÁRIO 
 *	|	ATRAVÉS DE TECNICAS DE REDES PARA ASSIM INTERCEPTAR OS DADOS TRAFEGADOS PELA APLICAÇÃO
 * 	|	PARA PREVINIR ISSO, DEVE-SE OBTER O PROTOCOLO HTTPS, QUE ASSEGURA A SEGURANÇA NO TRÁFEGO
 *	|	DE DADOS ENTRE O CLIENTE E O SERVIDOR, ATRAVÉS DE SSL E DE CERTIFICADO DIGITAL,
 *  |   ALÉM DE PERMITIR QUE O SISTEMA POSSA REALIZAR TRANSAÇÕES FINANCEIRAS COM SEGURANÇA 
 *  |   E DE SER CLASSIFICADO COMO SEGURO PELO GOOGLE CHROME
 *  |   OUTRA FORMA DE SE PREVINIR, É GERAR NOVOS ID DE SESSÃO A CADA LOGIN DO USUÁRIO, COMO
 *  |   SE FAZ ABAIXO. ISSO NÃO SUBSTITUI O NÍVEL DE PROTEÇÃO SSL DO PROTOCOLO HTTPS, MAS 
 *  |   DIFICULTA O ROUBO DA SESSÃO.
 *  |
 *  |	HTTPS - HYPER TEXT TRANSFER PROTOCOL SECURE
 *  |	SSL - SECURITY SOCKET LAYER
 *
 *	~GABRIEL MARTINS
 */	

session_start();
echo session_id();
session_destroy();

echo "<br>";

session_start();
session_regenerate_id();
echo session_id();